### ISSUE TITLE
Prepare for typst universe release

### ISSUE THREAD

**Issue by TomVer99** [TomVer99/FHICT-typst-template#84]
- [x] Move to kebab-case #83 
- [x] Move to the appropriate version number (most likely 0.10.0) #87 
- [x] Improve appendix heading "Appendix A: [chapter name]" #88 
- [x] Determine an appropriate name for the template on Typst Universe #89
